
INCLUDE(CheckLibraryExists)
INCLUDE(CheckIncludeFiles)

# check for zlib
CHECK_INCLUDE_FILES(zlib.h HAS_ZLIB_H)
CHECK_LIBRARY_EXISTS(z zlibVersion "" HAS_ZLIB)
IF(NOT HAS_ZLIB_H OR NOT HAS_ZLIB)
	MESSAGE(FATAL_ERROR "Missing zlib")
ENDIF(NOT HAS_ZLIB_H OR NOT HAS_ZLIB)

